/**
 * CANONICAL ECOSYSTEM REGISTRY — the sole public source of ecosystem truth.
 * Authority order position 4 (docs/canonical/ECOSYSTEM_AUTHORITY_ORDER.md).
 * Statuses follow docs/canonical/ENVIRONMENT_STATUS_STANDARD.md and are evidence-bound.
 * Destinations are never invented: null means no destination exists yet.
 */
import type { EcosystemEnvironment, ParticipationPathway } from './ecosystem-types.ts';

const REVIEWED = '2026-07-15';
const STEWARD_DIRECTIVE = 'Adopted steward decision — activation directive 2026-07-15';
const OWNER = 'Bridge Builders Collective founding stewardship';

/** Shared honest pathway for environments that exist only as adopted intentions. */
const interestPathway = (label = 'See the current contribution pathways'): ParticipationPathway => ({
  label,
  orientation: 'participate',
  href: '/contribute/',
  availableNow: true, // the orientation page exists and is truthful about what works
});

/** Helper for named branches adopted by steward decision with no implementation yet. */
function plannedBranch(
  id: string,
  name: string,
  shortDescription: string,
  fullDescription: string,
  overrides: Partial<EcosystemEnvironment> = {},
): EcosystemEnvironment {
  return {
    id,
    canonicalName: name,
    publicName: name,
    slug: id,
    shortDescription,
    fullDescription,
    status: 'planned',
    destination: null,
    frontDoorPath: `/ecosystem/${id}/`,
    audiences: ['individuals', 'communities'],
    capabilities: [],
    developing: ['Public description and program design are being prepared by stewards.'],
    participationPathways: [interestPathway()],
    relatedEnvironmentIds: [],
    parentEnvironmentId: 'bridge-builders-collective',
    publicOrder: 100,
    featured: false,
    accessNotice: 'This branch is an adopted intention. Nothing here is publicly usable yet.',
    trustNotice: null,
    canonicalOwner: OWNER,
    sourceAuthority: STEWARD_DIRECTIVE,
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: null,
    icon: null,
    ...overrides,
  };
}

export const ECOSYSTEM_REGISTRY: EcosystemEnvironment[] = [
  {
    id: 'bridge-builders-collective',
    canonicalName: 'Bridge Builders Collective',
    publicName: 'Bridge Builders Collective',
    slug: 'bridge-builders-collective',
    shortDescription:
      'A human-centered ecosystem supporting learning, regulation, stewardship, creativity, cultural continuity, shared knowledge, and meaningful participation.',
    fullDescription:
      'Bridge Builders Collective is the constitutional root of the ecosystem: human regulation infrastructure combining living archives, stewardship systems, governance frameworks, measurable-outcomes infrastructure, and continuity architecture. This front door is its canonical public presence.',
    status: 'in-development',
    destination: null,
    frontDoorPath: '/',
    audiences: [
      'individuals', 'families', 'young-people', 'elders', 'communities',
      'educators', 'creators', 'stewards', 'organizations', 'institutions',
    ],
    capabilities: [
      'Constitutional governance and canonical vocabulary (documented, committed)',
      'Public trust documentation: privacy, terms, retention, licensing, accessibility, incident response (draft, committed)',
      'This canonical front door (implemented; deployment pending steward action)',
    ],
    developing: [
      'Domain activation and public deployment',
      'Public contact pathway (no contact email or open submission channel exists yet; steward action pending)',
      'Downstream environments listed in the ecosystem overview',
    ],
    participationPathways: [
      { label: 'Explore the ecosystem', orientation: 'discover', href: '/ecosystem/', availableNow: true },
      { label: 'Read the principles', orientation: 'learn', href: '/principles/', availableNow: true },
      { label: 'Read the trust documents', orientation: 'discover', href: '/trust/', availableNow: true },
      { label: 'See the current contribution pathways', orientation: 'participate', href: '/contribute/', availableNow: true },
    ],
    relatedEnvironmentIds: ['system-rosetta-stone', 'bridgebuilders-academy', 'living-archive', 'sophia'],
    parentEnvironmentId: null,
    publicOrder: 0,
    featured: true,
    accessNotice:
      'The front door itself is in development: this site is real and its statements are canonical, but the ecosystem around it is at the stages each environment declares.',
    trustNotice:
      'Every status shown on this site follows the public Environment Status Standard. Nothing is described as operational without evidence.',
    canonicalOwner: OWNER,
    sourceAuthority: 'Bridge Builders Constitution §1 (docs/canonical/BRIDGE_BUILDERS_CONSTITUTION.md)',
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: { label: 'Explore the ecosystem', href: '/ecosystem/' },
    icon: '🌉',
  },
  {
    id: 'system-rosetta-stone',
    canonicalName: 'System Rosetta Stone',
    publicName: 'System Rosetta Stone',
    navLabel: 'Rosetta',
    slug: 'rosetta',
    shortDescription:
      'The human-meaning and relationship interpretation layer of Bridge Builders — understandable language, culturally aware interpretation, and guided pathways through complex knowledge.',
    fullDescription:
      'Rosetta is Bridge Builders Collective’s human-meaning and relationship interpretation layer. It supports understandable language, multilingual and culturally aware interpretation, context, nuance, lineage, relationships among principles, programs, practices, knowledge, and symbols, steward-reviewed mappings, and guided pathways through complex knowledge. Vocabulary and terminology explanation are functions of Rosetta — its first committed artifact is the Canonical Vocabulary — but Rosetta is not reduced to a vocabulary layer alone. Rosetta does not replace cultural authority, community interpretation, human relationship, or steward review.',
    status: 'in-development',
    destination: null,
    frontDoorPath: '/rosetta/',
    audiences: ['stewards', 'educators', 'organizations', 'institutions', 'creators'],
    capabilities: ['Canonical Vocabulary v1.0 (committed: docs/canonical/CANONICAL_VOCABULARY.md)'],
    developing: ['Public browsing experience for the vocabulary', 'Translation guides for institutional partners'],
    participationPathways: [
      { label: 'Read the canonical vocabulary source', orientation: 'learn', href: '/rosetta/', availableNow: true },
      interestPathway('See the current contribution pathways (vocabulary proposals)'),
    ],
    relatedEnvironmentIds: ['bridge-builders-collective', 'public-knowledge'],
    parentEnvironmentId: 'bridge-builders-collective',
    publicOrder: 10,
    featured: true,
    accessNotice: 'The vocabulary is public; the dedicated Rosetta environment is still being built.',
    trustNotice: null,
    canonicalOwner: OWNER,
    sourceAuthority: STEWARD_DIRECTIVE,
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: { label: 'See how we use language', href: '/rosetta/' },
    icon: '🪨',
  },
  {
    id: 'bridgebuilders-academy',
    canonicalName: 'BridgeBuilders Academy',
    publicName: 'BridgeBuilders Academy',
    navLabel: 'Academy',
    slug: 'academy',
    shortDescription: 'Where the ecosystem teaches — courses, practices, and orientation.',
    fullDescription:
      'BridgeBuilders Academy is the learning environment of the ecosystem: orientation for new participants, stewardship formation, and program-based learning. No course content is published yet; program design is an adopted intention.',
    status: 'planned',
    destination: null,
    frontDoorPath: '/academy/',
    audiences: ['individuals', 'young-people', 'educators', 'stewards', 'communities'],
    capabilities: [],
    developing: ['Curriculum design', 'Orientation pathway for new participants', 'Stewardship formation track'],
    participationPathways: [interestPathway('See the current contribution pathways (learning interest)')],
    relatedEnvironmentIds: ['programs', 'public-knowledge', 'bridge-builders-collective'],
    parentEnvironmentId: 'bridge-builders-collective',
    publicOrder: 20,
    featured: true,
    accessNotice: 'The Academy is planned. No courses are available yet; interest can be shared now.',
    trustNotice: null,
    canonicalOwner: OWNER,
    sourceAuthority: STEWARD_DIRECTIVE,
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: null,
    icon: '🎓',
  },
  {
    id: 'living-archive',
    canonicalName: 'The Living Archive',
    publicName: 'The Living Archive',
    navLabel: 'Living Archive',
    slug: 'archive',
    shortDescription: 'A living, consent-based archive of community memory across generations.',
    fullDescription:
      'The Living Archive preserves stories, media, and memory under contributor ownership, with consent, restricted-access protections, and archive-integrity guarantees. Its architecture, privacy protections, and media licensing terms are documented and committed; the archive software itself is not yet built.',
    status: 'planned',
    destination: null,
    frontDoorPath: '/archive/',
    audiences: ['families', 'elders', 'communities', 'creators', 'individuals'],
    capabilities: [
      'Archive governance documented (doc/ARCHITECTURE.md §4, PRIVACY_POLICY.md, MEDIA_LICENSING_POLICY.md — committed)',
    ],
    developing: ['Archive software (Supabase backend planned)', 'Contribution and consent flows', 'Family and restricted-access permissions'],
    participationPathways: [interestPathway('See the current contribution pathways (archive interest)')],
    relatedEnvironmentIds: ['story-circle', 'bridge-builders-collective'],
    parentEnvironmentId: 'bridge-builders-collective',
    publicOrder: 30,
    featured: true,
    accessNotice:
      'The Living Archive is planned. Its protections are already written; the software is not yet built. No submissions are accepted yet.',
    trustNotice: 'Archive materials are preservation assets, not extractive content assets (Constitution §7).',
    canonicalOwner: OWNER,
    sourceAuthority: STEWARD_DIRECTIVE,
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: null,
    icon: '📜',
  },
  {
    id: 'sophia',
    canonicalName: 'SOPHIA',
    publicName: 'SOPHIA',
    slug: 'sophia',
    shortDescription: 'An advisory presence that supports stewards and participants; humans make the decisions.',
    fullDescription:
      'SOPHIA is the ecosystem\'s advisory AI presence, constitutionally bounded: SOPHIA may not independently publish, approve, reject, discipline, diagnose, or make governance decisions (Constitution §9). SOPHIA is not yet implemented; her boundaries were written first, deliberately.',
    status: 'planned',
    destination: null,
    frontDoorPath: '/sophia/',
    audiences: ['stewards', 'individuals', 'communities'],
    capabilities: ['Advisory boundaries documented and constitutionally protected (committed)'],
    developing: ['Advisory implementation within the documented boundaries'],
    participationPathways: [
      { label: 'Read SOPHIA\'s constitutional boundaries', orientation: 'learn', href: '/sophia/', availableNow: true },
    ],
    relatedEnvironmentIds: ['bridge-builders-collective', 'system-rosetta-stone'],
    parentEnvironmentId: 'bridge-builders-collective',
    publicOrder: 40,
    featured: true,
    accessNotice: 'SOPHIA is planned. The boundaries are real and binding; the software does not exist yet.',
    trustNotice: 'SOPHIA is advisory only. Consequential decisions remain with human stewards, permanently.',
    canonicalOwner: OWNER,
    sourceAuthority: 'Bridge Builders Constitution §9; ' + STEWARD_DIRECTIVE,
    lastReviewed: REVIEWED,
    visibility: 'public',
    callToAction: null,
    icon: '🕊️',
  },

  // ——— Participation areas (registry-backed front-door sections) ———
  plannedBranch(
    'programs',
    'Programs',
    'Structured offerings the ecosystem will run — each published only when its pathway truly works.',
    'Programs are the structured, time-bounded offerings of the ecosystem (learning, practice, preservation). No program is currently open for paid enrollment; program titles listed in the ecosystem are adopted intentions unless their status says otherwise.',
    {
      status: 'in-development',
      frontDoorPath: '/programs/',
      publicOrder: 50,
      relatedEnvironmentIds: ['bridgebuilders-academy', 'synaptic-bridge', 'sun-reset'],
      capabilities: [
        'Two free public-preview participant experiences (Sun Reset, Synaptic Bridge) usable now on the current public application',
      ],
      accessNotice:
        'Programs are in development (status raised from planned on 2026-07-28 — evidence: two participant experiences are publicly usable in preview). No other program is open.',
      icon: '🧭',
    },
  ),
  plannedBranch(
    'public-knowledge',
    'Public Knowledge',
    'What the ecosystem knows, shared openly.',
    'Public Knowledge is the branch that maintains openly shared knowledge: principles, standards, vocabulary, and public documentation. Its first public materials are this site\'s principles, trust documents, and canonical standards.',
    {
      status: 'in-development',
      frontDoorPath: '/public-knowledge/',
      publicOrder: 60,
      capabilities: ['Principles, canonical standards, and trust documents published through this front door (committed)'],
      developing: ['A browsable public knowledge base beyond the founding documents'],
      participationPathways: [
        { label: 'Read the principles', orientation: 'learn', href: '/principles/', availableNow: true },
        { label: 'Read the trust documents', orientation: 'discover', href: '/trust/', availableNow: true },
      ],
      accessNotice: 'The founding documents are public now; the broader knowledge base is being built.',
      relatedEnvironmentIds: ['system-rosetta-stone', 'research'],
      icon: '📖',
    },
  ),
  plannedBranch(
    'research',
    'Research',
    'Evidence-informed study of regulation, continuity, and stewardship outcomes.',
    'The Research branch will develop the H-ROI (Human Return on Investment) measurement framework into practiced, ethical research. The H-ROI framework is documented and committed; no studies have been run and no outcomes are claimed.',
    {
      frontDoorPath: '/research/',
      publicOrder: 70,
      capabilities: ['H-ROI measurement framework documented (docs/H_ROI_METRICS.md — committed)'],
      developing: ['Research protocols and ethics review', 'First measured pilots'],
      relatedEnvironmentIds: ['public-knowledge'],
      icon: '🔬',
    },
  ),
  plannedBranch(
    'contribution',
    'Contribution',
    'The pathways by which people offer stories, media, effort, and stewardship to the ecosystem.',
    'Contribution governs how offerings enter the ecosystem: consented, licensed, revocable, and steward-reviewed. The licensing and privacy protections are committed; contribution software is not yet built. Today, the working public pathway is the repository-based interest pathway on the Contribute page.',
    {
      status: 'in-development',
      frontDoorPath: '/contribute/',
      publicOrder: 80,
      capabilities: ['Contribution protections documented (MEDIA_LICENSING_POLICY.md, PRIVACY_POLICY.md — committed)', 'The public repository is readable by anyone (verified 2026-07-15)'],
      developing: ['A working public submission pathway (issue creation is currently restricted on the repository; opening it — or publishing a contact email — is a pending steward action)', 'Structured contribution forms with consent capture'],
      participationPathways: [
        { label: 'Read the public repository', orientation: 'discover', href: 'https://github.com/selfcreation0891-eng/Bridge-Builders-Collective', availableNow: true },
        { label: 'Open a public conversation', orientation: 'participate', href: null, availableNow: false },
      ],
      accessNotice: 'Honest status: there is no open submission pathway yet. The repository is public and readable; posting to it is currently restricted, and no contact email is published. Opening a pathway is a named steward action.',
      relatedEnvironmentIds: ['living-archive', 'community-stewardship'],
      navLabel: 'Contribute',
      icon: '🤝',
    },
  ),
  plannedBranch(
    'community-stewardship',
    'Community Stewardship',
    'Communities caring for their own continuity.',
    'Community Stewardship develops stewardship practiced at community scale: local circles, shared archives, and community-held governance. The escalation and governance groundwork is committed; community programs are adopted intentions.',
    { frontDoorPath: '/community/', publicOrder: 55, relatedEnvironmentIds: ['relationship-stewardship', 'living-archive'], icon: '🏘️' },
  ),
  plannedBranch(
    'relationship-stewardship',
    'Relationship Stewardship',
    'Tending relationships so they last.',
    'Relationship Stewardship treats relationships as durable assets deserving deliberate care, drawing on Connective Dynamics.',
    { relatedEnvironmentIds: ['connective-dynamics', 'community-stewardship'] },
  ),

  // ——— Named branches adopted by steward decision (planned) ———
  plannedBranch(
    'institute-of-emotional-intelligence',
    'Institute of Emotional Intelligence',
    'Emotional intelligence as teachable, practicable infrastructure.',
    'The Institute of Emotional Intelligence is the adopted branch for emotional-intelligence learning and practice within the ecosystem.',
    { relatedEnvironmentIds: ['pattern-sync-for-self-build', 'bridgebuilders-academy'] },
  ),
  plannedBranch(
    'pattern-sync-for-self-build',
    'Pattern Sync for Self Build',
    'Learning your own patterns to build yourself deliberately.',
    'Pattern Sync for Self Build is the adopted practice branch for pattern recognition in service of deliberate self-construction. It makes no clinical or therapeutic claims.',
    { relatedEnvironmentIds: ['institute-of-emotional-intelligence'] },
  ),
  plannedBranch(
    'presence-principle',
    'Presence Principle',
    'Showing up matters: every presence is a gift.',
    'The Presence Principle branch develops the constitutional principle that presence itself is contribution.',
    { relatedEnvironmentIds: ['story-circle'] },
  ),
  plannedBranch(
    'connective-dynamics',
    'Connective Dynamics',
    'How relationships actually connect and hold.',
    'Connective Dynamics is the adopted branch studying how connections between people form and endure.',
    { relatedEnvironmentIds: ['relationship-stewardship', 'perspectouence'] },
  ),
  plannedBranch(
    'perspectouence',
    'Perspectouence',
    'A Bridge Builders original concept; its public articulation is being prepared.',
    'Perspectouence is an original term created within Bridge Builders Collective (canonical spelling preserved exactly). Its full public definition is pending steward articulation and will be published through the System Rosetta Stone.',
    { relatedEnvironmentIds: ['connective-dynamics', 'system-rosetta-stone'] },
  ),
  plannedBranch(
    'story-circle',
    'Story Circle',
    'A structured circle for telling and preserving stories.',
    'Story Circle is the adopted practice branch for structured shared storytelling, feeding — with consent — the Living Archive.',
    { relatedEnvironmentIds: ['living-archive', 'presence-principle'] },
  ),
  plannedBranch(
    'sun-reset',
    'Sun Reset',
    'A short guided reset session — the accessible entry environment for Synaptic Bridge.',
    'Sun Reset is a guided reset session inside Programs: eight calm, self-paced stages (arrival, grounding, breath, gentle activation, release, rhythm, downshift, reintegration). It is free, untimed, and requires no account; it also serves as the accessible entry environment for the Synaptic Bridge journey. It makes no therapeutic or outcome claims.',
    {
      status: 'public-preview',
      destination: 'https://bridgebuilderscollective.com/programs/sun-reset',
      capabilities: [
        'A public orientation page and guided session experience on the current public application',
        'Free, no account required, self-paced',
      ],
      developing: ['Steward review of the session content', 'Accessibility review of the guided experience'],
      participationPathways: [
        {
          label: 'Begin a Sun Reset session',
          orientation: 'participate',
          href: 'https://bridgebuilderscollective.com/programs/sun-reset',
          availableNow: true,
        },
      ],
      relatedEnvironmentIds: ['programs', 'synaptic-bridge'],
      parentEnvironmentId: 'programs',
      accessNotice:
        'Status raised from planned to public-preview on 2026-07-28 — evidence: the session route is live and publicly reachable on the current public application. Wording is conservative and flagged for steward review.',
      trustNotice: 'Nothing is timed, scored, or sold. This is a practice aid, not professional or medical care.',
      lastReviewed: '2026-07-28',
      sourceAuthority: 'Steward evidence review 2026-07-28 (route verified live) under founder revision directive',
    },
  ),
  plannedBranch(
    'savage2steward',
    'Savage2Steward',
    'An adopted branch of the ecosystem; public description is being prepared.',
    'Savage2Steward is a named branch adopted by steward decision. Its public description and program design are being prepared; nothing further is claimed yet.',
    { relatedEnvironmentIds: ['community-stewardship'] },
  ),
  plannedBranch(
    'equal-creative-opportunity',
    'Equal Creative Opportunity',
    'Everyone gets a real chance to create.',
    'Equal Creative Opportunity is both a constitutional principle and an adopted branch: equal access to creative means, not guaranteed equal outcomes.',
    { relatedEnvironmentIds: ['choice-creating-circumstances', 'creative-lab'] },
  ),
  plannedBranch(
    'choice-creating-circumstances',
    'Choice-Creating Circumstances',
    'Building circumstances where genuine choices exist.',
    'Choice-Creating Circumstances is the adopted branch for engineering conditions in which people have real choices.',
    { relatedEnvironmentIds: ['equal-creative-opportunity'] },
  ),
  plannedBranch(
    'open-participation',
    'Open Participation',
    'Anyone may take part; authority is earned through stewardship, not access.',
    'Open Participation develops the constitutional principle that participation is open to the public without invitation — and that openness does not confer authority.',
    { relatedEnvironmentIds: ['contribution'] },
  ),
  plannedBranch(
    'creative-lab',
    'Creative Lab',
    'An adopted branch of the ecosystem; public description is being prepared.',
    'Creative Lab is a named branch adopted by steward decision. Its public description is being prepared; nothing further is claimed yet.',
    { relatedEnvironmentIds: ['equal-creative-opportunity'] },
  ),
  plannedBranch(
    'bridgeview-media',
    'BRIDGEview',
    'The media branch of the ecosystem; public description is being prepared.',
    'BRIDGEview is the adopted media branch of the ecosystem. Its public description and editorial standards are being prepared; nothing further is claimed yet.',
  ),
  plannedBranch(
    'resonate-touch',
    'Resonate Touch',
    'An adopted branch of the ecosystem; public description is being prepared.',
    'Resonate Touch is a named branch adopted by steward decision. Its public description is being prepared; nothing further is claimed yet.',
  ),
  {
    // Registered per founder decision F-1 (2026-07-27). Evidence: live public route
    // on the current public application; no pricing, eligibility, or outcome claims exist there.
    id: 'synaptic-bridge',
    canonicalName: 'Synaptic Bridge',
    publicName: 'Synaptic Bridge',
    slug: 'synaptic-bridge',
    shortDescription:
      'A 21-day self-paced continuity journey — presence, pattern, and contribution across three seven-day arcs.',
    fullDescription:
      'Synaptic Bridge is a participant experience inside Programs: a 21-day continuity journey moving through three seven-day arcs (Return to Presence, Pattern Sync for Self Build, Bridge into Contribution). Days are untimed and may be entered in any order; progress is kept privately on the participant’s own device; contribution is optional and consent-based. It is free to use and makes no outcome promises.',
    status: 'public-preview',
    destination: 'https://bridgebuilderscollective.com/programs/synaptic-bridge',
    frontDoorPath: '/ecosystem/synaptic-bridge/',
    audiences: ['individuals', 'young-people', 'communities'],
    capabilities: [
      'A 21-day self-paced journey with daily orientation, practice, and reflection (live on the current public application)',
      'Private on-device progress marking; no account required',
      'An accessible entry session (Sun Reset) and an optional, consent-based contribution pathway',
    ],
    developing: [
      'Steward review flow for offered contributions',
      'Integration with the Living Archive for consented offerings',
    ],
    participationPathways: [
      {
        label: 'Enter the 21-day journey',
        orientation: 'participate',
        href: 'https://bridgebuilderscollective.com/programs/synaptic-bridge',
        availableNow: true,
      },
      {
        label: 'Begin with a Sun Reset session',
        orientation: 'discover',
        href: 'https://bridgebuilderscollective.com/programs/sun-reset',
        availableNow: true,
      },
    ],
    relatedEnvironmentIds: ['programs', 'sun-reset', 'contribution'],
    parentEnvironmentId: 'programs',
    publicOrder: 52,
    featured: false,
    accessNotice:
      'First registration (founder decision F-1, 2026-07-27): status and wording are deliberately conservative and flagged for steward review.',
    trustNotice:
      'Journey progress is stored only on your own device. Contribution is optional and consent-based. Nothing is timed, scored, or sold.',
    canonicalOwner: OWNER,
    sourceAuthority: 'Founder decision F-1 — Synaptic Bridge registration (2026-07-27)',
    lastReviewed: '2026-07-27',
    visibility: 'public',
    callToAction: { label: 'Enter Synaptic Bridge', href: 'https://bridgebuilderscollective.com/programs/synaptic-bridge' },
    icon: null,
  },
];
